# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# This builds a docker image containing all the tools we need to run our
# test suite in CI, including rust, kotlin, and swift.

FROM cimg/rust:1.66.0

ENV \
    # Some APT packages like 'tzdata' wait for user input on install by default.
    # https://stackoverflow.com/questions/44331836/apt-get-install-tzdata-noninteractive
    DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

# already installed in cimg: libcurl4, python3, git, curl, unzip, g++
RUN sudo apt-get update -qq \
    && sudo apt-get install -qy --no-install-recommends \
        clang \
        openjdk-11-jdk-headless \
        ruby \
        ruby-dev \
        # Swift dependencies
        libtinfo5 \
        libncurses5 \
        python3-pip \
    && sudo apt-get clean

# This should automatically install the version specified in rust-toolchain.toml
ADD rust-toolchain.toml rust-toolchain.toml
RUN rustup self update \
  && rustup update \
  && rustup show \
  && rm rust-toolchain.toml
